version: '3.9'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_strong_password123!
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Your_strong_password123! -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - mssqldata:/var/opt/mssql
  authapi:
    build:
      context: .
      dockerfile: ./src/NiceDentist.Auth.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AuthDb=Server=sqlserver;Database=NiceDentistAuthDb;User Id=sa;Password=Your_strong_password123!;TrustServerCertificate=True;
      - Jwt__Key=please-change-in-prod-very-secret
      - Jwt__Issuer=NiceDentist
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
volumes:
  mssqldata:
